[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
version = "0"
name = "kak-tts"
dependencies = [
  "TTS",
]


[project.scripts]
tts_server = "tts_server:main"


[tool.setuptools]
py-modules = ["tts_server"]